$(document).ready(function(){$('#sidebarCollapse').on('click',function(){if($("body").attr("data-theme")=="dark"){$("body").attr("data-theme","light");}else{$("body").attr("data-theme","dark");}});twemoji.parse(document.body);});$(document).on("change","#customRange1",function(){var mycustomora=$(this).val();cambiaSfondoOra(mycustomora);});function cambiaSfondoOra(ora){var mypos=ora*100/24;$(".liveSfondo").css("background-position-y",mypos+"%");$("#provino").text(ora);if(ora<3||ora>18)
{$("body").attr("data-theme","dark");$(".nuvolaVolante").fadeOut(300);$(".sfondoRight").css("background-image","url('/template/img/hotel_night_snow.gif')");}else{$(".nuvolaVolante").fadeIn(300);$(".sfondoRight").css("background-image","url('/template/img/hotel.gif')");$("body").attr("data-theme","light");}}
function autoCheckLive(){var giorno=new Date();var ora=giorno.getHours();var mypos=ora*100/24;$(".liveSfondo").css("background-position-y",mypos+"%");$("#provino").text(ora);if(ora<3||ora>20)
{$("body").attr("data-theme","dark");$(".nuvolaVolante").fadeOut(300);$(".sfondoRight").css("background-image","url('/template/img/hotel_night_snow.gif')");}else{$(".nuvolaVolante").fadeIn(300);$(".sfondoRight").css("background-image","url('/template/img/hotel.gif')");$("body").attr("data-theme","light");}}
setInterval(autoCheckLive(),15*60*1000);function bbnotifica(tipo,titolo,testo){var altezza=130;var attivi=$('.notificaBB').length;var top=(altezza*attivi)+30;var notifica='<div class="notificaBB '+tipo+' entraNot" style="top:'+top+'px;">';notifica+='<div class="row rigaNotifiche">';notifica+='<div class="col-lg-3 col-3 iconaNotifiche"></div>';notifica+='<div class="col-lg-7 contenutoNotifica">';notifica+='<span class="titleNotifica">'+titolo+'</span>';notifica+='<div class="testNotifica">'+testo+'</div></div>';notifica+='<div class="col-lg-2 col-2 chiudiNotifica"><span>»</span></div>';notifica+='</div></div>';$(".wrapper").append(notifica);}
$(document).on("click",".notificaBB",function(){var notifica=$(this);notifica.addClass("eliminaNotifica");setTimeout(function(){notifica.remove();},500);});function throttle(f,delay){var timer=null;return function(){var context=this,args=arguments;clearTimeout(timer);timer=window.setTimeout(function(){f.apply(context,args);},delay||500);};}
$(document).on("keyup",".cercaUtente",throttle(function(){var cercato=$(this).val();if(cercato.length>0){$.ajax({type:"POST",url:"/ajax/cercaUtente.php",data:{cercato:cercato},success:function(result){$(".wrapRisultatiRicerca").html(result);$(".wrapRisultatiRicerca").show();}});}else{$(".wrapRisultatiRicerca").html();$(".wrapRisultatiRicerca").hide();}}));var observer=new IntersectionObserver((entries,observer)=>{entries.forEach(entry=>{if(entry.intersectionRatio>0.0){img=entry.target;if(!img.hasAttribute('src')){img.setAttribute('src',img.dataset.src);}}});},{})
for(let img of document.getElementsByTagName('img')){observer.observe(img);}
$(document).on("click",".btnNotifiche",function(){var route="/ajax/getNotifiche.php";$(".overlaySito").fadeIn();$(".modalDestra").toggleClass("modalVisibile");$(".modalDestra").load(route,function(responseTxt,statusTxt,jqXHR){if(statusTxt=="success"){}
if(statusTxt=="error"){alert("Error: "+jqXHR.status+" "+jqXHR.statusText);}});})
$(document).on("click",".overlaySito",function(){$(".modalDestra").removeClass("modalVisibile");$(".modalCentro").fadeOut(300);$(".overlaySito").fadeOut(600);setTimeout(function(){$(".modalDestra").html("");},600);setTimeout(function(){$(".modalCentro").html("");},600);})
$(document).on("click",".notifica",function()
{var not=$(this).attr('not');$.ajax({type:"POST",url:"/ajax/cleanot.php",data:{not:not},success:function(result){}});});window.onscroll=function(){scrollando()};var header=document.getElementById("headerbobba");var sticky=header.offsetTop;function scrollando(){if(window.pageYOffset>sticky){$(".tornaAlto").fadeIn();}else{$(".tornaAlto").hide();}}